### ISSUE TITLE
Create a Google Sheet template

### ISSUE THREAD

**Issue by alicelovescake** [alicelovescake/sheetmenu#5]
We don't want users to manage the organization of their Google Sheet. Thus, we need a template that will get cloned upon account creation. This will allow users to get up and running by simply editing the sheet.

**Comment by amorriscode** [comment]
We will want to [add protection in the template](https://www.howtogeek.com/412399/how-to-protect-cells-from-editing-in-google-sheets) so some columns/sheets cannot be edited.
