### ISSUE TITLE
Add restaurant settings page

### ISSUE THREAD

**Issue by alicelovescake** [alicelovescake/sheetmenu#8]
As a user, I want to enter and edit my restaurant information.

**Comment by amorriscode** [comment]
Users should manage their subscription from the settings page.

**Comment by alicelovescake** [comment]
Create new end point for updating information

**Comment by amorriscode** [comment]
Let's have the menu broken up into sections similar to this design: https://dribbble.com/shots/15186840-Setting-page-example.

You can see an example of how to select between different components to render here: https://github.com/amorriscode/tavern/blob/main/web/src/components/AuthModal/AuthModal.js.
